### ISSUE TITLE
Dude, Come help us

### ISSUE THREAD

**Issue by afiaka87** [yashbonde/dall-e-baby#4]
I help out with the DALLE-pytorch project by @lucidrains. Someone linked me to this page yesterday and wow - you've done a lot of useful work here. 

Would you be interested in helping us to get a large enough dataset to train on? Now that we have a pretrained VAE from OpenAI (and an awesome 1024 token pretrained VAE from the taming-transformers research), momentum has really picked up and we're basically ready to train. We just need the dataset. It's gotta be humongous per the OpenAI paper. I've done some mild training myself and it has a lot of trouble generalizing without: a huge batch_size (they use 512 in the paper) and a _very large_ dataset. That's kind of the key insight from their recent efforts - big enough data generalizes. 

Also - WIT came out today as well, and it's going to highly similar to what OpenAI scraped from wikipedia themselves. Exciting times.

At any rate, it would be awesome if you could help us with the datasets. It seems like you've figured out how to generate a good deal of captions even for datasets that don't include captions, which I now realize OpenAI must have done a good deal of. Feel free to stop by: 

https://github.com/lucidrains/DALLE-pytorch/issues

**Comment by robvanvolt** [comment]
I agree with @afiaka87 !
Let's recreate Open-AI Dall-E or even develop a better version than the original Dall-E!
