### ISSUE TITLE
Code that would be great to include in DALLE-pytorch

### ISSUE THREAD

**Issue by afiaka87** [yashbonde/dall-e-baby#5]
Hey @yashbonde, I'm having a lot of trouble navigating DALLE-pytorch discussions right now so I'm just gonna leave this here. I'm gonna spend a bit perusing your code for promising candidates to include in DALLE-pytorch. 

lucidrains is a pretty busy dude. I don't believe he's really working on DALLE-pytorch this week as he has about fifty other repositories he keeps up with and is (understandably) more concerned with his protein folding efforts which arguably have a great impact. 

anway, that's a lengthy way of me saying that I've found the best way to get something into one of his repositories is to just build it and make a pull request. Then he'll be able to discuss any ideas with you on the PR. 

I'll make another post here in a bit and I guess try communicating with me either here or in the *Issues* section of DALLE-pytorch. I'm starting to loathe Github's implementation of "Discussions".

**Comment by afiaka87** [comment]
easiest way to get ahold of me is probably on EleutherAI's discord. I dont want that info linked to my Github, but if you join as yashbonde, I'll reach out.

**Comment by afiaka87** [comment]
@yashbonde 

Okay, so it's looking like basically all of `generate_captions.py` would be useful in DALLE-pytorch.

**Comment by afiaka87** [comment]
@yashbonde 
Scripting out download.txt properly would be fantastic as well - but I saw your notice about how that stuff is really just a bunch of lines you need to parallelize yourself, so that's tricky. 

Do you know the rough disk usage of both the tar files and the untarred versions combined? Separate is useful too, i suppose. That's info I and others need when, for instance, setting up a cloud GPU instance.

**Comment by yashbonde** [comment]
Technically you can use the `download.txt` however to get the maximum benefit you would want to download multiple torrents in parallel which is what makes it challenging. Please feel free to use `generate_captions.py` as you see fit. Rough disk usage if I remember correctly was ~80GB at full size, it's been a time and I also use vast.ai.

**Comment by yashbonde** [comment]
I've joined in the discord.

**Comment by robvanvolt** [comment]
You might want to join the discord @yashbonde where we would have more direct communication streams! :-)
https://discord.gg/xtjwjHVU
